import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { Outfit } from "next/font/google";
import { ToastContainer, Slide } from "react-toastify";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <GoogleOneTap/> 
      <body
        className={` antialiased`}
      >
        <Navbar></Navbar>
                    <ToastContainer
              position="top-right"
              autoClose={1500}
              limit={3}
              hideProgressBar={false}
              newestOnTop={true}
              closeOnClick={true}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover={false}
              theme="colored"
              transition={Slide}
            />
       <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
